name: CI(pylightnet)

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 0 0 * * 1
  
jobs:
  linter_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install pylightnet without build
        working-directory: ./python
        env:
          SKIP_EXT: "1"
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev]

      - name: Run the formatter
        working-directory: ./python
        run: |
          python -m ruff format . --check --diff

      - name: Run the linter
        working-directory: ./python
        run: |
          python -m ruff check . --output-format=github

      - name: Run the tests
        working-directory: ./python
        run: |
          python -m pytest tests